# Utiliza una imagen de Node.js más reciente como base
FROM node:16

# Establece el directorio de trabajo en el contenedor
WORKDIR /app

# Copia el archivo package.json y package-lock.json al directorio de trabajo
COPY package*.json ./

# Instala Prisma CLI globalmente
RUN npm install -g prisma@latest
RUN npm install @prisma/client@5.14.0 --save

# Instala las dependencias del proyecto
RUN npm install

# Copia el resto de los archivos al directorio de trabajo
COPY . .

# Genera el cliente de Prisma
RUN prisma generate

# Expone el puerto en el que se ejecuta la aplicación
EXPOSE 3000

# Comando para ejecutar la aplicación
CMD ["npm", "start"]
