global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'pedidos'
    static_configs:
      - targets: ['host.docker.internal:5010']
  - job_name: 'compras'
    static_configs:
      - targets: ['host.docker.internal:5009']
  - job_name: 'usuarios'
    static_configs:
      - targets: ['host.docker.internal:5007']
  - job_name: 'inventario'
    metrics_path: '/q/metrics'
    static_configs:
      - targets: ['host.docker.internal:5014']
  - job_name: 'DatosUsuarios'
    metrics_path: '/q/metrics'
    static_configs:
      - targets: ['host.docker.internal:5012']
  - job_name: 'DatosClasificacion'
    metrics_path: '/q/metrics'
    static_configs:
      - targets: ['host.docker.internal:5013']
  - job_name: 'DatosCompra'
    metrics_path: '/q/metrics'
    static_configs:
      - targets: ['host.docker.internal:5015']
  - job_name: 'Transporte'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:5003']
  - job_name: 'Estadisticas'
    metrics_path: '/q/metrics'
    static_configs:
      - targets: ['host.docker.internal:5016']
  - job_name: 'clasificaciones'
    metrics_path: '/q/metrics'
    static_configs:
      - targets: ['host.docker.internal:5013']
