global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'pedidos'
    static_configs:
      - targets: ['host.docker.internal:5010']
  - job_name: 'compras'
    static_configs:
      - targets: ['host.docker.internal:5011']
  - job_name: 'usuarios'
    static_configs:
      - targets: ['host.docker.internal:5007']

  