version: "3.8"

services:
  compras:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - miportal
    labels:
      - "traefik.http.routers.compras.rule=Host(`Miportal.compras.localhost`)"
      - "traefik.http.services.compras.loadbalancer.server.port=9080"

networks:
  miportal:
    external: true