version: "3.8"

services:
  compras:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9080"
    networks:
      - miportal
    labels:
      - "traefik.http.routers.compras.rule=Host(`Miportal.compras.localhost`)"

networks:
  miportal:
    external: true