# Usa la imagen oficial de Python como base
FROM python:3.10

# Copiar el script ORM al contenedor
COPY ms_db_config/orm_db_create.py /app/orm_db_create.py

# Instalar psycopg2
RUN pip install psycopg2-binary

# Comando por defecto
CMD [ "python", "/app/orm_db_create.py" ]
