FROM maven AS buildjar

WORKDIR /opt/app

COPY . /opt/app

RUN mvn clean package

# Start with a base image containing Java runtime
FROM openjdk:21-jdk-slim

# Add Maintainer Info
LABEL maintainer="email@example.com"

# Add a volume pointing to /tmp
VOLUME /tmp

# Make port 8080 available to the world outside this container
EXPOSE 5003

# The application's jar file
ARG JAR_FILE=/opt/app/target/*.jar

# Add the application's jar to the container
COPY --from=buildjar ${JAR_FILE} app.jar

# Run the jar file 
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]