version: "3.8"

services:
  pedidos:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9080:9080"
    networks:
      - miportal
    labels:
      - "traefik.http.routers.pedidos.rule=Host(`Miportal.pedidos.localhost`)"

networks:
  miportal:
    external: true