version: '3.7'

services:
  cockroachdb:
    image: cockroachdb/cockroach:v21.2.8
    container_name: cockroachdb
    command: start-single-node --insecure
    ports:
      - "26257:26257"
      - "8080:8080"
    volumes:
      - cockroach-data:/cockroach/cockroach-data

volumes:
  cockroach-data:`