version: '3.8'
services:
  cockroachdb:
    image: cockroachdb/cockroach
    restart: always
    ports:
      - "26257:26257"
      - "8080:8080"
    expose:
      - 26257
    command: start-single-node --insecure
    volumes:
      - ./data_init/test_sql:/docker-entrypoint-initdb.d
  # db_init:
  #   build:
  #     context: ./data_init
  #     dockerfile: Dockerfile
  #   restart: on-failure
  #   environment:
  #     - DATABASE_URL=postgresql://root@cockroachdb:26257/db
  #   depends_on:
  #     - cockroachdb
  adminer:
    image: adminer
    ports:
      - 8081:8080
    restart: always

